name: CI

on: 
  pull_request:
    branches:
      -dev
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Spring Boot Tests
      run: mvn clean test
  
