INSERT into users(user_id, display_name, username, password_hash, available_cash, committed_cash)values (100, 'TEST TARGET 1', 'TEST TARGET 1', 'BLAH', 10000, 0)
INSERT into users(user_id, display_name, username, password_hash, available_cash, committed_cash)values (200, 'TEST TARGET 2', 'TEST TARGET 2', 'BLAH', 10000, 0)
INSERT into users(user_id, display_name, username, password_hash, available_cash, committed_cash)values (300, 'TEST TARGET 3', 'TEST TARGET 3', 'BLAH', 10000, 0)

INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (1, 'Modifier 1', 'Modifier Description', 500)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (2, 'Modifier 2', 'Modifier Description', 400)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (3, 'Modifier 3', 'Modifier Description', 300)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (4, 'Modifier 4', 'Modifier Description', 200)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (5, 'Modifier 5', 'Modifier Description', 100)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (6, 'Modifier 6', 'Modifier Description', 500)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (7, 'Modifier 7', 'Modifier Description', 400)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (8, 'Modifier 8', 'Modifier Description', 300)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (9, 'Modifier 9', 'Modifier Description', 200)
INSERT into modifiers(modifier_id, modifier_title, modifier_description, modifier_value) values (10, 'Modifier 10', 'Modifier Description', 100)
